# Puerto para testing
server.port=8082

# Logging para test: nivel INFO (menos detalles que DEBUG)
logging.level.root=INFO
logging.level.com.example.usermanagement=INFO

# Aquí puedes poner configuración específica para test
